# Generated by Django 4.1.5 on 2023-04-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_category_blog_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Places', models.CharField(max_length=255, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.categorie'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
