# Generated by Django 4.1.5 on 2023-04-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_categorie_alter_blog_places_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Places',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=255)),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.categorie')),
            ],
        ),
    ]
