# Generated by Django 4.1.5 on 2023-04-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_categorie_places_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hotel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blogapp.hotel'),
            preserve_default=False,
        ),
    ]
